export const mockStudents = [
  {
    id: "S001",
    name: "Raj Patel",
    email: "raj.patel@email.com",
    phone: "+91-9876543210",
    roomNumber: "301",
    checkInDate: "2024-11-01",
    courseName: "B.Tech CSE",
    university: "Delhi University",
    status: "Active",
    messSubscription: "Premium",
    paymentStatus: "Paid",
  },
  {
    id: "S002",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+91-9876543211",
    roomNumber: "205",
    checkInDate: "2024-10-15",
    courseName: "B.Com",
    university: "Delhi University",
    status: "Active",
    messSubscription: "Standard",
    paymentStatus: "Paid",
  },
  {
    id: "S003",
    name: "Arjun Singh",
    email: "arjun.singh@email.com",
    phone: "+91-9876543212",
    roomNumber: "412",
    checkInDate: "2024-11-05",
    courseName: "B.Tech ECE",
    university: "Delhi University",
    status: "Active",
    messSubscription: "Premium",
    paymentStatus: "Pending",
  },
  {
    id: "S004",
    name: "Sneha Gupta",
    email: "sneha.gupta@email.com",
    phone: "+91-9876543213",
    roomNumber: "108",
    checkInDate: "2024-09-20",
    courseName: "B.Tech Mechanical",
    university: "Delhi University",
    status: "Active",
    messSubscription: "Standard",
    paymentStatus: "Paid",
  },
  {
    id: "S005",
    name: "Vikram Kumar",
    email: "vikram.kumar@email.com",
    phone: "+91-9876543214",
    roomNumber: "215",
    checkInDate: "2024-10-01",
    courseName: "MBA",
    university: "Delhi University",
    status: "Active",
    messSubscription: "Premium",
    paymentStatus: "Paid",
  },
  {
    id: "S006",
    name: "Ananya Desai",
    email: "ananya.desai@email.com",
    phone: "+91-9876543215",
    roomNumber: "320",
    checkInDate: "2024-08-15",
    courseName: "B.Tech IT",
    university: "Delhi University",
    status: "Active",
    messSubscription: "Standard",
    paymentStatus: "Paid",
  },
]

export const mockRooms = [
  {
    roomNumber: "301",
    capacity: "Single",
    type: "AC",
    occupants: ["S001"],
    occupancy: "1/1",
    status: "Occupied",
    rent: "₹8,000",
  },
  {
    roomNumber: "205",
    capacity: "Double",
    type: "Non-AC",
    occupants: ["S002"],
    occupancy: "1/2",
    status: "Available",
    rent: "₹5,000",
  },
  {
    roomNumber: "412",
    capacity: "Single",
    type: "AC",
    occupants: ["S003"],
    occupancy: "1/1",
    status: "Occupied",
    rent: "₹8,000",
  },
  {
    roomNumber: "108",
    capacity: "Double",
    type: "AC",
    occupants: ["S004"],
    occupancy: "1/2",
    status: "Available",
    rent: "₹7,500",
  },
  {
    roomNumber: "215",
    capacity: "Single",
    type: "Non-AC",
    occupants: ["S005"],
    occupancy: "1/1",
    status: "Occupied",
    rent: "₹4,500",
  },
  {
    roomNumber: "320",
    capacity: "Double",
    type: "AC",
    occupants: ["S006"],
    occupancy: "1/2",
    status: "Available",
    rent: "₹7,500",
  },
]

export const mockMess = [
  {
    studentId: "S001",
    studentName: "Raj Patel",
    roomNumber: "301",
    plan: "Premium",
    mealsDays: 30,
    mealsWeekly: "All meals (B, L, D)",
    amount: "₹3,500",
    status: "Active",
  },
  {
    studentId: "S002",
    studentName: "Priya Sharma",
    roomNumber: "205",
    plan: "Standard",
    mealsDays: 30,
    mealsWeekly: "Lunch & Dinner",
    amount: "₹2,000",
    status: "Active",
  },
  {
    studentId: "S003",
    studentName: "Arjun Singh",
    roomNumber: "412",
    plan: "Premium",
    mealsDays: 30,
    mealsWeekly: "All meals (B, L, D)",
    amount: "₹3,500",
    status: "Active",
  },
  {
    studentId: "S004",
    studentName: "Sneha Gupta",
    roomNumber: "108",
    plan: "Standard",
    mealsDays: 30,
    mealsWeekly: "Lunch & Dinner",
    amount: "₹2,000",
    status: "Active",
  },
  {
    studentId: "S005",
    studentName: "Vikram Kumar",
    roomNumber: "215",
    plan: "Premium",
    mealsDays: 30,
    mealsWeekly: "All meals (B, L, D)",
    amount: "₹3,500",
    status: "Active",
  },
  {
    studentId: "S006",
    studentName: "Ananya Desai",
    roomNumber: "320",
    plan: "Standard",
    mealsDays: 30,
    mealsWeekly: "Lunch & Dinner",
    amount: "₹2,000",
    status: "Active",
  },
]

export const mockPayments = [
  {
    id: "P001",
    studentId: "S001",
    studentName: "Raj Patel",
    roomNumber: "301",
    roomRent: "₹8,000",
    messCharges: "₹3,500",
    otherCharges: "₹500",
    totalAmount: "₹12,000",
    dueDate: "2024-12-01",
    status: "Paid",
    paidDate: "2024-11-25",
  },
  {
    id: "P002",
    studentId: "S002",
    studentName: "Priya Sharma",
    roomNumber: "205",
    roomRent: "₹5,000",
    messCharges: "₹2,000",
    otherCharges: "₹300",
    totalAmount: "₹7,300",
    dueDate: "2024-12-01",
    status: "Paid",
    paidDate: "2024-11-20",
  },
  {
    id: "P003",
    studentId: "S003",
    studentName: "Arjun Singh",
    roomNumber: "412",
    roomRent: "₹8,000",
    messCharges: "₹3,500",
    otherCharges: "₹500",
    totalAmount: "₹12,000",
    dueDate: "2024-12-01",
    status: "Pending",
    paidDate: null,
  },
  {
    id: "P004",
    studentId: "S004",
    studentName: "Sneha Gupta",
    roomNumber: "108",
    roomRent: "₹7,500",
    messCharges: "₹2,000",
    otherCharges: "₹400",
    totalAmount: "₹9,900",
    dueDate: "2024-12-01",
    status: "Paid",
    paidDate: "2024-11-18",
  },
  {
    id: "P005",
    studentId: "S005",
    studentName: "Vikram Kumar",
    roomNumber: "215",
    roomRent: "₹4,500",
    messCharges: "₹3,500",
    otherCharges: "₹250",
    totalAmount: "₹8,250",
    dueDate: "2024-12-01",
    status: "Paid",
    paidDate: "2024-11-22",
  },
  {
    id: "P006",
    studentId: "S006",
    studentName: "Ananya Desai",
    roomNumber: "320",
    roomRent: "₹7,500",
    messCharges: "₹2,000",
    otherCharges: "₹400",
    totalAmount: "₹9,900",
    dueDate: "2024-12-01",
    status: "Paid",
    paidDate: "2024-11-15",
  },
]
